### ISSUE TITLE
potential problem of multiple commits pushed?

### ISSUE THREAD

**Issue by chenyong** [MarceloPrado/has-changed-path#3] opened 2020-03-11 09:45 UTC
I read the code it's like reading the latest commit hash a path:

```bash
git log -1 --format=format:%H --full-diff $PATHS_TO_SEARCH
```

so is there any case that I push 2 commits to different paths, say in a single PR, and only the last changed paths are detected?

**Comment by chenyong** [comment] 2020-03-11 10:36
A bit weird that I used in in our private repo and it returned all paths not changed, in PR and after merged. I did change one of the PRs. It's not showing commits in the logs so I don't know if it grabbed wrong hash. only suspicious log:

```
Code in the following paths has not changed:
account
```

**Comment by MarceloPrado** [comment] 2020-03-13 19:48
Hi @chenyong, yes, for the current version only the latest commit is read.
I could not find a good and reliable way to fix this, although I have not spent much time on this problem. 

In my current workflow, when I'm merging a PR, I usually squash all commits into one before merging. This fixes the issue, but I'm aware it's not the ideal fix.

Regarding your merged PR not spotting changes, what type of merge commit you did? If the latest commit did not change anything in path, this action will not work. You'd have to squash them before merging.

**Comment by chenyong** [comment] 2020-03-16 03:03
> You'd have to squash them before merging.

No I didn't squash. And a "merged" commit is generated, it might cause problems.

We don't squash most of the time. Different way of using Git flow...

Can't say I located the problem. But we had to try other ways..

**Comment by MarceloPrado** [comment] 2020-03-21 11:42
I'll let you know here if I discover a better solution. My apologies for not having this figured it out already!

**Comment by MarceloPrado** [comment] 2020-04-03 22:13
Hi @chenyong , sorry for the delay. Things here have been a bit busy.
I have some good news for you: the issue is now fixed by https://github.com/MarceloPrado/has-changed-path/pull/4.

Let me know if you have any other problems with this.

Cheers,
Marcelo

**Closed by MarceloPrado** 2020-04-03 22:13 UTC

**Comment by chenyong** [comment] 2020-04-07 03:05
Thanks anyway.

**Comment by chenyong** [comment] 2020-06-03 02:40
I'm trying making a JavaScript version of this action for our own use case, maybe useful for your side as well, JavaScript has more controls on logics https://github.com/jimengio/pr-file-change-action#L14 .
